// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckAppVersion():Promise<string>;

export function CheckPaymentStatus():Promise<boolean>;

export function CheckVerisonOnStartup():Promise<void>;

export function DownloadNewVersion(arg1:string):Promise<void>;

export function GetPacientsData(arg1:string):Promise<main.PacientsData>;

export function GetUpdateStatus():Promise<boolean|string>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:main.Credentials):Promise<boolean>;

export function SaveScreenshot(arg1:string,arg2:string):Promise<string>;

export function SearchDiseases(arg1:string):Promise<Array<main.SearchItem>>;

export function SearchTreatments(arg1:string):Promise<Array<main.SearchItem>>;

export function SendMail(arg1:main.EmailData):Promise<string>;

export function StorePacientsData(arg1:main.PacientsData):Promise<string>;
