// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAppVersion() {
  return window['go']['main']['App']['CheckAppVersion']();
}

export function CheckPaymentStatus() {
  return window['go']['main']['App']['CheckPaymentStatus']();
}

export function CheckVerisonOnStartup() {
  return window['go']['main']['App']['CheckVerisonOnStartup']();
}

export function DownloadNewVersion(arg1) {
  return window['go']['main']['App']['DownloadNewVersion'](arg1);
}

export function GetPacientsData(arg1) {
  return window['go']['main']['App']['GetPacientsData'](arg1);
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function SaveScreenshot(arg1, arg2) {
  return window['go']['main']['App']['SaveScreenshot'](arg1, arg2);
}

export function SearchDiseases(arg1) {
  return window['go']['main']['App']['SearchDiseases'](arg1);
}

export function SearchTreatments(arg1) {
  return window['go']['main']['App']['SearchTreatments'](arg1);
}

export function SendMail(arg1) {
  return window['go']['main']['App']['SendMail'](arg1);
}

export function StorePacientsData(arg1) {
  return window['go']['main']['App']['StorePacientsData'](arg1);
}
