// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SaveScreenshot(arg1:string,arg2:string):Promise<string>;

export function SendMail(arg1:main.EmailData):Promise<string>;
